"""
Self-authored module registry.

Tracks modules generated by the meta-agent, including provenance:
which prompt produced it, which model, timestamp, test results.
"""

import json
import time
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

META_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "meta"


@dataclass
class AuthoredModule:
    name: str
    description: str
    path: str
    version: str = "0.1.0"
    status: str = "draft"  # draft, testing, approved, rejected, active
    provenance: Dict[str, Any] = field(default_factory=dict)
    tests_passed: bool = False
    test_output: str = ""
    created_at: float = 0.0
    approved_at: Optional[float] = None
    created_by: str = "meta-agent"

    def to_dict(self) -> Dict:
        return {
            "name": self.name,
            "description": self.description,
            "path": self.path,
            "version": self.version,
            "status": self.status,
            "provenance": self.provenance,
            "tests_passed": self.tests_passed,
            "test_output": self.test_output[:1000],
            "created_at": self.created_at,
            "approved_at": self.approved_at,
            "created_by": self.created_by,
        }


class ModuleRegistry:
    """Registry of self-authored modules."""

    def __init__(self, registry_dir: Optional[Path] = None):
        self._dir = registry_dir or META_DIR
        self._dir.mkdir(parents=True, exist_ok=True)
        self._registry_path = self._dir / "modules.json"
        self._modules: Dict[str, AuthoredModule] = {}
        self._load()

    def _load(self):
        if self._registry_path.exists():
            try:
                data = json.loads(self._registry_path.read_text(encoding="utf-8"))
                for name, mod_data in data.items():
                    self._modules[name] = AuthoredModule(**mod_data)
            except Exception as e:
                logger.error(f"Failed to load module registry: {e}")

    def _save(self):
        data = {name: mod.to_dict() for name, mod in self._modules.items()}
        self._registry_path.write_text(json.dumps(data, indent=2, default=str))

    def register(self, module: AuthoredModule):
        module.created_at = module.created_at or time.time()
        self._modules[module.name] = module
        self._save()

    def get(self, name: str) -> Optional[AuthoredModule]:
        return self._modules.get(name)

    def update_status(self, name: str, status: str):
        mod = self._modules.get(name)
        if mod:
            mod.status = status
            if status == "approved":
                mod.approved_at = time.time()
            self._save()

    def list_modules(self, status: Optional[str] = None) -> List[AuthoredModule]:
        modules = list(self._modules.values())
        if status:
            modules = [m for m in modules if m.status == status]
        return modules

    def get_pending_review(self) -> List[AuthoredModule]:
        return self.list_modules(status="testing")

    def remove(self, name: str):
        self._modules.pop(name, None)
        self._save()


_registry: Optional[ModuleRegistry] = None


def get_module_registry() -> ModuleRegistry:
    global _registry
    if _registry is None:
        _registry = ModuleRegistry()
    return _registry
