"""
Meta Registry - Tracks self-authored modules and their provenance
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass, field
from pathlib import Path

from ..logging import get_logger

logger = get_logger("meta.registry")


@dataclass
class ModuleRecord:
    """Provenance record for a self-authored module."""
    name: str
    description: str
    status: str  # draft, testing, approved, rejected, active
    source_prompt: str
    model_used: str
    created_at: str
    approved_at: Optional[str] = None
    rejected_at: Optional[str] = None
    test_results: Optional[Dict] = None
    review_notes: str = ""
    version: str = "0.1.0"


class MetaRegistry:
    """
    Registry for tracking self-authored modules.

    Stores provenance metadata for every module generated by the meta-agent:
    which prompt produced it, which model, timestamp, test results.
    """

    def __init__(self, registry_path: Optional[str] = None):
        self.registry_path = registry_path or os.getenv(
            "ONEAGENT_META_REGISTRY", "./oneagent_meta_registry.json"
        )
        self._records: Dict[str, ModuleRecord] = {}
        self._load()

    def _load(self):
        """Load registry from disk."""
        path = Path(self.registry_path)
        if not path.exists():
            return

        try:
            with open(path, "r") as f:
                data = json.load(f)

            for name, record_data in data.get("modules", {}).items():
                self._records[name] = ModuleRecord(
                    name=record_data.get("name", name),
                    description=record_data.get("description", ""),
                    status=record_data.get("status", "draft"),
                    source_prompt=record_data.get("source_prompt", ""),
                    model_used=record_data.get("model_used", ""),
                    created_at=record_data.get("created_at", ""),
                    approved_at=record_data.get("approved_at"),
                    rejected_at=record_data.get("rejected_at"),
                    test_results=record_data.get("test_results"),
                    review_notes=record_data.get("review_notes", ""),
                    version=record_data.get("version", "0.1.0"),
                )

            logger.info(f"Loaded {len(self._records)} meta module records")
        except Exception as e:
            logger.warning(f"Failed to load meta registry: {e}")

    def _save(self):
        """Save registry to disk."""
        data = {
            "modules": {
                name: {
                    "name": r.name,
                    "description": r.description,
                    "status": r.status,
                    "source_prompt": r.source_prompt,
                    "model_used": r.model_used,
                    "created_at": r.created_at,
                    "approved_at": r.approved_at,
                    "rejected_at": r.rejected_at,
                    "test_results": r.test_results,
                    "review_notes": r.review_notes,
                    "version": r.version,
                }
                for name, r in self._records.items()
            }
        }

        Path(self.registry_path).parent.mkdir(parents=True, exist_ok=True)
        with open(self.registry_path, "w") as f:
            json.dump(data, f, indent=2)

    def register(self, record: ModuleRecord):
        """Register a new module record."""
        self._records[record.name] = record
        self._save()
        logger.info(f"Registered meta module: {record.name}")

    def get(self, name: str) -> Optional[ModuleRecord]:
        """Get a module record by name."""
        return self._records.get(name)

    def list_modules(self, status: Optional[str] = None) -> List[ModuleRecord]:
        """List all modules, optionally filtered by status."""
        records = list(self._records.values())
        if status:
            records = [r for r in records if r.status == status]
        return records

    def approve(self, name: str) -> bool:
        """Mark a module as approved."""
        record = self._records.get(name)
        if record:
            record.status = "active"
            record.approved_at = datetime.now().isoformat()
            self._save()
            return True
        return False

    def reject(self, name: str, reason: str = "") -> bool:
        """Mark a module as rejected."""
        record = self._records.get(name)
        if record:
            record.status = "rejected"
            record.rejected_at = datetime.now().isoformat()
            record.review_notes = reason
            self._save()
            return True
        return False

    def remove(self, name: str) -> bool:
        """Remove a module from the registry."""
        if name in self._records:
            del self._records[name]
            self._save()
            return True
        return False
